version: 2
updates:

  # actions (master)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(action):"
    target-branch: "sync-with-upstream"
